### ISSUE TITLE
Bug: misusing break statement

### ISSUE THREAD

**Issue by lo0pring** [LoopringSecondary/relay#288]
https://github.com/Loopring/relay/blob/39be0d2c5c253f20a5583109c8f7bce36e6250c5/ethaccessor/gasprice_evaluator.go#L54

https://github.com/Loopring/relay/blob/727d709d1ea865766806e466b69b8de9928b7899/marketcap/capprovider.go#L148

Those break statements are invalid, please check the codebase to make sure stop those goroutines correctly.

**Comment by lydy** [comment]
yes, you are right.
I'll fix it.
thank you.
