### ISSUE TITLE
一些报错，需要请教下

### ISSUE THREAD

**Issue by tianheng2017** [LoopringSecondary/relay#290]
配置文件：
[keystore]
    keydir = "/root/go/src/github.com/Loopring/relay/ks_dir"

keystore文件已放在ks_dir目录里面

执行：
build/bin/relay account import 

报错：error:keystore file can't empty

执行第二句：
build/bin/relay  --mode=miner --unlocks $mineraddress --passwords $passwords

报错：error:--passwords is not a HexAddress

**Comment by tianheng2017** [comment]
不好意思 我没装gcc，搞定了

**Comment by tianheng2017** [comment]
还有这个错误：
 fatal   ERR Client sent AUTH, but no password is set

**Comment by tianheng2017** [comment]
还有ipfs启动后的报错：
root@localhost:~# ipfs daemon --enable-pubsub-experiment
Initializing daemon...
Adjusting current ulimit to 2048...
Successfully raised file descriptor limit to 2048.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/45.33.30.68/tcp/4001
Swarm listening on /ip6/2600:3c00::f03c:91ff:fe72:a182/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit/ipfs/QmVWZPJLdpvDiLdKVRrAaBfxtaQtyPZm5q2hnVWqdEWC9G
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/45.33.30.68/tcp/4001
Swarm announcing /ip6/2600:3c00::f03c:91ff:fe72:a182/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
01:55:33.568 ERROR   floodsub: error reading rpc from <peer.ID a5efEQ>: connection reset comm.go:36
01:59:26.698 ERROR   floodsub: error reading rpc from <peer.ID aosc64>: connection reset comm.go:36
01:59:27.412 ERROR   floodsub: error reading rpc from <peer.ID aw98zm>: connection reset comm.go:36
..........

**Comment by lydy** [comment]
error:keystore file can't empty 的问题，可能是因为配置文件没有加载正确，试下使用参数 --config指定配置文件
error:--passwords is not a HexAddress 的问题，参数格式应该是这样的，--unlocks "0xba2244d9Cd504252aee8FA92F8D5523C248c78B2" --passwords "1"

ipfs的这个错误没有影响的

**Comment by tianheng2017** [comment]
感谢！真是一点即通

**Comment by tianheng2017** [comment]
root@localhost:~/go/src/github.com/Loopring/relay# build/bin/relay account import --datadir keystore.json
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.importAccount(0xc4200aa420)
        /root/go/src/github.com/Loopring/relay/cmd/lrc/accountcmd.go:120 +0x5fa
github.com/Loopring/relay/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xa58500, 0xca10d8, 0xc4200aa420, 0xc42007e900, 0x0)
        /root/go/src/github.com/Loopring/relay/vendor/gopkg.in/urfave/cli.v1/app.go:492 +0x7c
github.com/Loopring/relay/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xb58613, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb602c8, 0x14, 0x0, ...)
        /root/go/src/github.com/Loopring/relay/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0xa95
github.com/Loopring/relay/vendor/gopkg.in/urfave/cli%2ev1.(*App).RunAsSubcommand(0xc4200949c0, 0xc4200aa000, 0x0, 0x0)
        /root/go/src/github.com/Loopring/relay/vendor/gopkg.in/urfave/cli.v1/app.go:379 +0xa7b
github.com/Loopring/relay/vendor/gopkg.in/urfave/cli%2ev1.Command.startApp(0xb58bec, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb5ca08, 0xf, 0x0, ...)
        /root/go/src/github.com/Loopring/relay/vendor/gopkg.in/urfave/cli.v1/command.go:298 +0x944
github.com/Loopring/relay/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xb58bec, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb5ca08, 0xf, 0x0, ...)
        /root/go/src/github.com/Loopring/relay/vendor/gopkg.in/urfave/cli.v1/command.go:98 +0x1318
github.com/Loopring/relay/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200944e0, 0xc4200a00f0, 0x5, 0x5, 0x0, 0x0)
        /root/go/src/github.com/Loopring/relay/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6f8
main.main()
        /root/go/src/github.com/Loopring/relay/cmd/lrc/main.go:57 +0x7a2

**Comment by tianheng2017** [comment]
搞定了，原来需要这样：
build/bin/relay account import --datadir keystore.json --pk 私钥

**Comment by tianheng2017** [comment]
现在就这一个错误了：
2018-03-10T02:39:40.837Z        fatal   ERR Client sent AUTH, but no password is set

不知道怎么处理！

**Comment by tianheng2017** [comment]
衷心的感谢，relay跑起来了！

**Comment by tianheng2017** [comment]
2018-03-31T14:00:59.475Z        fatal   can't sync marketcap with error:invalid character '<' looking for beginning of value

这是什么错误？

**Comment by tianheng2017** [comment]
start_block_number = 33287
    end_block_number = 0
    confirm_block_number = 5
    debug = false
    save_event_log = true
    use_test_start_block_number = false
顺便介绍下这几个参数的意义吧
