### ISSUE TITLE
mac下编译失败

### ISSUE THREAD

**Issue by tianheng2017** [LoopringSecondary/relay#359]
administratordeMacBook-Air:relay administrator$ make relay
/bin/sh build/prepare.sh
go build -ldflags -s -v -o build/bin/relay cmd/lrc/*
vendor/github.com/ethereum/go-ethereum/common/mclock/mclock.go:23:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/aristanetworks/goarista/monotime" and "github.com/Loopring/relay/vendor/github.com/aristanetworks/goarista/monotime"
vendor/github.com/ethereum/go-ethereum/accounts/accounts.go:23:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum"
cmd/lrc/nodecmd.go:33:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/accounts" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/accounts"
cmd/lrc/accountcmd.go:29:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/accounts/keystore" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/accounts/keystore"
vendor/github.com/ethereum/go-ethereum/interfaces.go:25:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/common" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/common"
vendor/github.com/ethereum/go-ethereum/common/types.go:26:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/common/hexutil" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/common/hexutil"
vendor/github.com/ethereum/go-ethereum/crypto/crypto.go:32:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/common/math" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/common/math"
vendor/github.com/ethereum/go-ethereum/event/subscription.go:24:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/common/mclock" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/common/mclock"
vendor/github.com/ethereum/go-ethereum/interfaces.go:26:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/core/types" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/core/types"
vendor/github.com/ethereum/go-ethereum/core/types/bloom9.go:24:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/crypto" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/crypto"
vendor/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:41:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/crypto/randentropy" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/crypto/randentropy"
vendor/github.com/ethereum/go-ethereum/crypto/signature_cgo.go:27:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1"
vendor/github.com/ethereum/go-ethereum/common/types.go:27:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/crypto/sha3" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/crypto/sha3"
vendor/github.com/ethereum/go-ethereum/accounts/accounts.go:26:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/event" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/event"
vendor/github.com/ethereum/go-ethereum/trie/proof.go:25:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/log" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/log"
vendor/github.com/ethereum/go-ethereum/core/types/transaction_signing.go:27:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/params" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/params"
vendor/github.com/ethereum/go-ethereum/crypto/crypto.go:34:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/rlp" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/rlp"
vendor/github.com/ethereum/go-ethereum/core/types/derive_sha.go:24:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/ethereum/go-ethereum/trie" and "github.com/Loopring/relay/vendor/github.com/ethereum/go-ethereum/trie"
vendor/github.com/ethereum/go-ethereum/log/handler.go:11:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/go-stack/stack" and "github.com/Loopring/relay/vendor/github.com/go-stack/stack"
vendor/github.com/ethereum/go-ethereum/accounts/keystore/key.go:35:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/pborman/uuid" and "github.com/Loopring/relay/vendor/github.com/pborman/uuid"
vendor/github.com/ethereum/go-ethereum/trie/trie.go:27:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/rcrowley/go-metrics" and "github.com/Loopring/relay/vendor/github.com/rcrowley/go-metrics"
vendor/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:25:2: case-insensitive import collision: "github.com/loopring/relay/vendor/github.com/rjeczalik/notify" and "github.com/Loopring/relay/vendor/github.com/rjeczalik/notify"
vendor/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:43:2: case-insensitive import collision: "github.com/loopring/relay/vendor/golang.org/x/crypto/pbkdf2" and "github.com/Loopring/relay/vendor/golang.org/x/crypto/pbkdf2"
vendor/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:44:2: case-insensitive import collision: "github.com/loopring/relay/vendor/golang.org/x/crypto/scrypt" and "github.com/Loopring/relay/vendor/golang.org/x/crypto/scrypt"
vendor/github.com/ethereum/go-ethereum/accounts/keystore/account_cache.go:34:2: case-insensitive import collision: "github.com/loopring/relay/vendor/gopkg.in/fatih/set.v0" and "github.com/Loopring/relay/vendor/gopkg.in/fatih/set.v0"
vendor/github.com/ethereum/go-ethereum/trie/sync.go:24:2: case-insensitive import collision: "github.com/loopring/relay/vendor/gopkg.in/karalabe/cookiejar.v2/collections/prque" and "github.com/Loopring/relay/vendor/gopkg.in/karalabe/cookiejar.v2/collections/prque"
cmd/lrc/accountcmd.go:33:2: case-insensitive import collision: "github.com/loopring/relay/vendor/gopkg.in/urfave/cli.v1" and "github.com/Loopring/relay/vendor/gopkg.in/urfave/cli.v1"
make: *** [relay] Error 1

**Comment by tianheng2017** [comment]
哦  搞定了，需要sudo make relay

**Comment by mmmmmagina** [comment]
👍
