### ISSUE TITLE
这样就算启动成功了吗？

### ISSUE THREAD

**Issue by tianheng2017** [LoopringSecondary/relay#378]
![qidong](https://user-images.githubusercontent.com/29515610/38492788-a8daec88-3c22-11e8-8dcd-60ce9cbe2541.png)

撮合成功后命令行会有提示吗？是不是可以执行redis命令keys *查看本机订单池的信息？

![kong](https://user-images.githubusercontent.com/29515610/38492879-e265b370-3c22-11e8-9f62-a872196ce2d0.png)

过几天应该就有数据了

**Comment by lydy** [comment]
算是启动成功，但是订单池是在mysql.lpr_orders 中，而不是在redis里
所有撮合的环路都会记录在mysql.lpr_ring_submit_infos中

**Comment by tianheng2017** [comment]
![mysql](https://user-images.githubusercontent.com/29515610/38763922-7ad018c2-3fd8-11e8-9992-eaf9bf3f4a44.png)
跑了一晚上，所有表里面一个数据也没有，正常吗？

**Comment by tianheng2017** [comment]
还有个问题是跑relay的过程中，硬盘数据变得越来越大，应该是eth在同步区块，可以不同步区块也能撮合吗？好像我ssd只有120g明显不够用
